package generator

// embeddedTemplates returns the template contents keyed by name.
// Templates are defined as string constants to keep the POC simple.
// These can be migrated to go:embed files later if template complexity grows.
func embeddedTemplates() map[string]string {
	return map[string]string{
		"file":          fileTemplate,
		"session":       sessionTemplate,
		"helpers":       helpersTemplate,
		"getapp":        getAppTemplate,
		"getapps":       getAppsTemplate,
		"getorg":        getOrgTemplate,
		"getorgs":       getOrgsTemplate,
		"getspace":      getSpaceTemplate,
		"getspaces":     getSpacesTemplate,
		"getservice":    getServiceTemplate,
		"getservices":   getServicesTemplate,
		"getorgusers":   getOrgUsersTemplate,
		"getspaceusers": getSpaceUsersTemplate,
	}
}

const fileTemplate = `// Code generated by cf-plugin-migrate — DO NOT EDIT.
//
// Source: cf-plugin-migrate.yml
{{- range .Methods}}
// {{.Name}}: {{apiCalls .}}
{{- end}}

package {{.Package}}

import (
	"code.cloudfoundry.org/cli/plugin"
	plugin_models "code.cloudfoundry.org/cli/plugin/models"
{{- if .HasDomain}}
	"context"
{{- end}}
{{- if .NeedsStrings}}
	"strings"
{{- end}}
{{- if .NeedsTime}}
	"time"
{{- end}}
{{- if .HasDomain}}

	"github.com/cloudfoundry/go-cfclient/v3/client"
	"github.com/cloudfoundry/go-cfclient/v3/config"
{{- end}}
)

// Ensure plugin_models import is used even when no domain methods are configured.
var _ plugin_models.Organization

{{template "session" .}}
`

const sessionTemplate = `
// V2Compat implements plugin.CliConnection by wrapping the original RPC
// connection for session/context methods and replacing domain methods
// with direct CAPI V3 calls via go-cfclient.
type V2Compat struct {
	conn      plugin.CliConnection
{{- if .HasDomain}}
	cfClient  *client.Client
	spaceGUID string
	orgGUID   string
{{- end}}
}

// NewV2Compat creates a V2Compat that wraps the given CliConnection.
{{- if .HasDomain}}
// It initializes a go-cfclient client using the session's access token
// and API endpoint for CAPI V3 domain method calls.
func NewV2Compat(conn plugin.CliConnection) (*V2Compat, error) {
	endpoint, err := conn.ApiEndpoint()
	if err != nil {
		return nil, err
	}

	token, err := conn.AccessToken()
	if err != nil {
		return nil, err
	}
	// AccessToken() returns "bearer <token>" — go-cfclient expects the token without the prefix.
	if len(token) > 7 {
		token = token[7:]
	}

	cfg, err := config.New(endpoint, config.Token(token, ""), config.SkipTLSValidation())
	if err != nil {
		return nil, err
	}

	cfClient, err := client.New(cfg)
	if err != nil {
		return nil, err
	}

	compat := &V2Compat{
		conn:     conn,
		cfClient: cfClient,
	}

	org, err := conn.GetCurrentOrg()
	if err != nil {
		return nil, err
	}
	compat.orgGUID = org.Guid

	space, err := conn.GetCurrentSpace()
	if err != nil {
		return nil, err
	}
	compat.spaceGUID = space.Guid

	return compat, nil
}
{{- else}}
func NewV2Compat(conn plugin.CliConnection) (*V2Compat, error) {
	return &V2Compat{conn: conn}, nil
}
{{- end}}

// --- Session/context methods (pass-through to original connection) ---

func (c *V2Compat) GetCurrentOrg() (plugin_models.Organization, error) {
	return c.conn.GetCurrentOrg()
}

func (c *V2Compat) GetCurrentSpace() (plugin_models.Space, error) {
	return c.conn.GetCurrentSpace()
}

func (c *V2Compat) Username() (string, error) {
	return c.conn.Username()
}

func (c *V2Compat) UserGuid() (string, error) {
	return c.conn.UserGuid()
}

func (c *V2Compat) UserEmail() (string, error) {
	return c.conn.UserEmail()
}

func (c *V2Compat) IsLoggedIn() (bool, error) {
	return c.conn.IsLoggedIn()
}

func (c *V2Compat) IsSSLDisabled() (bool, error) {
	return c.conn.IsSSLDisabled()
}

func (c *V2Compat) HasOrganization() (bool, error) {
	return c.conn.HasOrganization()
}

func (c *V2Compat) HasSpace() (bool, error) {
	return c.conn.HasSpace()
}

func (c *V2Compat) ApiEndpoint() (string, error) {
	return c.conn.ApiEndpoint()
}

func (c *V2Compat) ApiVersion() (string, error) {
	return c.conn.ApiVersion()
}

func (c *V2Compat) HasAPIEndpoint() (bool, error) {
	return c.conn.HasAPIEndpoint()
}

func (c *V2Compat) LoggregatorEndpoint() (string, error) {
	return c.conn.LoggregatorEndpoint()
}

func (c *V2Compat) DopplerEndpoint() (string, error) {
	return c.conn.DopplerEndpoint()
}

func (c *V2Compat) AccessToken() (string, error) {
	return c.conn.AccessToken()
}

// --- CLI passthrough methods (pass-through to original connection) ---

func (c *V2Compat) CliCommand(args ...string) ([]string, error) {
	return c.conn.CliCommand(args...)
}

func (c *V2Compat) CliCommandWithoutTerminalOutput(args ...string) ([]string, error) {
	return c.conn.CliCommandWithoutTerminalOutput(args...)
}

// --- Domain methods (CAPI V3 via go-cfclient) ---
// Domain methods below are generated based on cf-plugin-migrate.yml.
// Methods not listed in the YAML fall through to the original connection.

func (c *V2Compat) GetApp(appName string) (plugin_models.GetAppModel, error) {
{{- $hasGetApp := false}}
{{- range .Methods}}{{if eq .Name "GetApp"}}{{$hasGetApp = true}}{{end}}{{end}}
{{- if $hasGetApp}}
	return c.getApp(appName)
{{- else}}
	return c.conn.GetApp(appName)
{{- end}}
}

func (c *V2Compat) GetApps() ([]plugin_models.GetAppsModel, error) {
{{- $hasGetApps := false}}
{{- range .Methods}}{{if eq .Name "GetApps"}}{{$hasGetApps = true}}{{end}}{{end}}
{{- if $hasGetApps}}
	return c.getApps()
{{- else}}
	return c.conn.GetApps()
{{- end}}
}

func (c *V2Compat) GetOrg(orgName string) (plugin_models.GetOrg_Model, error) {
{{- $hasGetOrg := false}}
{{- range .Methods}}{{if eq .Name "GetOrg"}}{{$hasGetOrg = true}}{{end}}{{end}}
{{- if $hasGetOrg}}
	return c.getOrg(orgName)
{{- else}}
	return c.conn.GetOrg(orgName)
{{- end}}
}

func (c *V2Compat) GetOrgs() ([]plugin_models.GetOrgs_Model, error) {
{{- $hasGetOrgs := false}}
{{- range .Methods}}{{if eq .Name "GetOrgs"}}{{$hasGetOrgs = true}}{{end}}{{end}}
{{- if $hasGetOrgs}}
	return c.getOrgs()
{{- else}}
	return c.conn.GetOrgs()
{{- end}}
}

func (c *V2Compat) GetSpace(spaceName string) (plugin_models.GetSpace_Model, error) {
{{- $hasGetSpace := false}}
{{- range .Methods}}{{if eq .Name "GetSpace"}}{{$hasGetSpace = true}}{{end}}{{end}}
{{- if $hasGetSpace}}
	return c.getSpace(spaceName)
{{- else}}
	return c.conn.GetSpace(spaceName)
{{- end}}
}

func (c *V2Compat) GetSpaces() ([]plugin_models.GetSpaces_Model, error) {
{{- $hasGetSpaces := false}}
{{- range .Methods}}{{if eq .Name "GetSpaces"}}{{$hasGetSpaces = true}}{{end}}{{end}}
{{- if $hasGetSpaces}}
	return c.getSpaces()
{{- else}}
	return c.conn.GetSpaces()
{{- end}}
}

func (c *V2Compat) GetService(serviceInstance string) (plugin_models.GetService_Model, error) {
{{- $hasGetService := false}}
{{- range .Methods}}{{if eq .Name "GetService"}}{{$hasGetService = true}}{{end}}{{end}}
{{- if $hasGetService}}
	return c.getService(serviceInstance)
{{- else}}
	return c.conn.GetService(serviceInstance)
{{- end}}
}

func (c *V2Compat) GetServices() ([]plugin_models.GetServices_Model, error) {
{{- $hasGetServices := false}}
{{- range .Methods}}{{if eq .Name "GetServices"}}{{$hasGetServices = true}}{{end}}{{end}}
{{- if $hasGetServices}}
	return c.getServices()
{{- else}}
	return c.conn.GetServices()
{{- end}}
}

func (c *V2Compat) GetOrgUsers(orgName string, args ...string) ([]plugin_models.GetOrgUsers_Model, error) {
{{- $hasGetOrgUsers := false}}
{{- range .Methods}}{{if eq .Name "GetOrgUsers"}}{{$hasGetOrgUsers = true}}{{end}}{{end}}
{{- if $hasGetOrgUsers}}
	return c.getOrgUsers(orgName, args...)
{{- else}}
	return c.conn.GetOrgUsers(orgName, args...)
{{- end}}
}

func (c *V2Compat) GetSpaceUsers(orgName string, spaceName string) ([]plugin_models.GetSpaceUsers_Model, error) {
{{- $hasGetSpaceUsers := false}}
{{- range .Methods}}{{if eq .Name "GetSpaceUsers"}}{{$hasGetSpaceUsers = true}}{{end}}{{end}}
{{- if $hasGetSpaceUsers}}
	return c.getSpaceUsers(orgName, spaceName)
{{- else}}
	return c.conn.GetSpaceUsers(orgName, spaceName)
{{- end}}
}

{{template "helpers" .}}

{{range .Methods}}
{{- if eq .Name "GetApp"}}{{template "getapp" .}}{{end}}
{{- if eq .Name "GetApps"}}{{template "getapps" .}}{{end}}
{{- if eq .Name "GetOrg"}}{{template "getorg" .}}{{end}}
{{- if eq .Name "GetOrgs"}}{{template "getorgs" .}}{{end}}
{{- if eq .Name "GetSpace"}}{{template "getspace" .}}{{end}}
{{- if eq .Name "GetSpaces"}}{{template "getspaces" .}}{{end}}
{{- if eq .Name "GetService"}}{{template "getservice" .}}{{end}}
{{- if eq .Name "GetServices"}}{{template "getservices" .}}{{end}}
{{- if eq .Name "GetOrgUsers"}}{{template "getorgusers" .}}{{end}}
{{- if eq .Name "GetSpaceUsers"}}{{template "getspaceusers" .}}{{end}}
{{end}}
`

const getOrgsTemplate = `
// getOrgs lists all organizations the user has access to.
// Populates: {{join .Fields ", "}} (1 V3 API call).
func (c *V2Compat) getOrgs() ([]plugin_models.GetOrgs_Model, error) {
	orgs, err := c.cfClient.Organizations.ListAll(context.Background(), nil)
	if err != nil {
		return nil, err
	}

	result := make([]plugin_models.GetOrgs_Model, len(orgs))
	for i, org := range orgs {
		result[i] = plugin_models.GetOrgs_Model{
{{- if hasField . "Guid"}}
			Guid: org.GUID,
{{- end}}
{{- if hasField . "Name"}}
			Name: org.Name,
{{- end}}
		}
	}
	return result, nil
}
`

const getSpacesTemplate = `
// getSpaces lists all spaces the user has access to.
// Populates: {{join .Fields ", "}} (1 V3 API call).
func (c *V2Compat) getSpaces() ([]plugin_models.GetSpaces_Model, error) {
	spaces, err := c.cfClient.Spaces.ListAll(context.Background(), nil)
	if err != nil {
		return nil, err
	}

	result := make([]plugin_models.GetSpaces_Model, len(spaces))
	for i, space := range spaces {
		result[i] = plugin_models.GetSpaces_Model{
{{- if hasField . "Guid"}}
			Guid: space.GUID,
{{- end}}
{{- if hasField . "Name"}}
			Name: space.Name,
{{- end}}
		}
	}
	return result, nil
}
`

// helpersTemplate outputs helper functions conditionally.
// It receives TemplateData (not ResolvedMethod).
// helpersTemplate outputs pointer-dereference helper functions used by
// domain method templates to safely handle nullable V3 API fields.
const helpersTemplate = `
{{- if .HasDomain}}

// Pointer-dereference helpers for nullable V3 API fields.
func ptrStr(s *string) string { if s != nil { return *s }; return "" }
func ptrInt(v *int) int { if v != nil { return *v }; return 0 }
func ptrInt64(v *int) int64 { if v != nil { return int64(*v) }; return 0 }

// Ensure helpers are used even if no domain method references all of them.
var (
	_ = ptrStr
	_ = ptrInt
	_ = ptrInt64
)
{{- end}}
`

const getAppTemplate = `
// getApp looks up a single application by name in the current space.
// Populates: {{join .Fields ", "}} ({{groupCount .}} V3 API call(s)).
func (c *V2Compat) getApp(appName string) (plugin_models.GetAppModel, error) {
	app, err := c.cfClient.Applications.Single(context.Background(), &client.AppListOptions{
		Names:      client.Filter{Values: []string{appName}},
		SpaceGUIDs: client.Filter{Values: []string{c.spaceGUID}},
	})
	if err != nil {
		return plugin_models.GetAppModel{}, err
	}

	result := plugin_models.GetAppModel{
{{- if hasField . "Guid"}}
		Guid: app.GUID,
{{- end}}
{{- if hasField . "Name"}}
		Name: appName,
{{- end}}
{{- if hasField . "State"}}
		State: app.State,
{{- end}}
{{- if hasField . "SpaceGuid"}}
		SpaceGuid: c.spaceGUID,
{{- end}}
	}

{{- if hasGroup . 6}}
	// Env group: get environment variables.
	env, err := c.cfClient.Applications.GetEnvironmentVariables(context.Background(), app.GUID)
	if err != nil {
		return result, err
	}
	result.EnvironmentVars = make(map[string]interface{})
	for k, v := range env {
		result.EnvironmentVars[k] = v
	}
{{- end}}

{{- if hasGroup . 5}}
	// Package group: get the latest package for PackageUpdatedAt.
	pkgs, err := c.cfClient.Packages.ListForAppAll(context.Background(), app.GUID, nil)
	if err != nil {
		return result, err
	}
	if len(pkgs) > 0 {
		pkg := pkgs[len(pkgs)-1]
		result.PackageUpdatedAt = &pkg.UpdatedAt
	}
{{- end}}

{{- if hasGroup . 3}}
	// Droplet group: get current droplet for buildpack, package state, staging info.
	droplet, err := c.cfClient.Droplets.GetCurrentForApp(context.Background(), app.GUID)
	if err != nil {
		return result, err
	}
{{- if hasField . "PackageState"}}
	result.PackageState = string(droplet.State)
{{- end}}
{{- if hasField . "StagingFailedReason"}}
	result.StagingFailedReason = ptrStr(droplet.Error)
{{- end}}
{{- if hasField . "BuildpackUrl"}}
	if len(droplet.Buildpacks) > 0 {
		result.BuildpackUrl = droplet.Buildpacks[0].Name
	}
{{- end}}
{{- end}}

{{- if hasGroup . 4}}
	// Stack group: look up the stack by name from the droplet.
	stack, err := c.cfClient.Stacks.Single(context.Background(), &client.StackListOptions{
		Names: client.Filter{Values: []string{droplet.Stack}},
	})
	if err != nil {
		return result, err
	}
	result.Stack = &plugin_models.GetApp_Stack{
		Guid:        stack.GUID,
		Name:        stack.Name,
		Description: ptrStr(stack.Description),
	}
{{- end}}

{{- if hasGroup . 1}}
	// Process group: get process details (command, memory, disk, instances, health check).
	processes, _, err := c.cfClient.Processes.ListForApp(context.Background(), app.GUID, nil)
	if err != nil {
		return result, err
	}
	if len(processes) > 0 {
		process, err := c.cfClient.Processes.Get(context.Background(), processes[0].GUID)
		if err != nil {
			return result, err
		}
{{- if hasField . "DiskQuota"}}
		result.DiskQuota = int64(process.DiskInMB)
{{- end}}
{{- if hasField . "InstanceCount"}}
		result.InstanceCount = process.Instances
{{- end}}
{{- if hasField . "Memory"}}
		result.Memory = int64(process.MemoryInMB)
{{- end}}
{{- if hasField . "HealthCheckTimeout"}}
		result.HealthCheckTimeout = ptrInt(process.HealthCheck.Data.Timeout)
{{- end}}
{{- if hasField . "Command"}}
		result.Command = ptrStr(process.Command)
{{- end}}
{{- if hasField . "DetectedStartCommand"}}
		result.DetectedStartCommand = ptrStr(process.Command)
{{- end}}

{{- if hasGroup . 2}}
		// Stats group: get process stats for running instances.
		stats, err := c.cfClient.Processes.GetStats(context.Background(), processes[0].GUID)
		if err != nil {
			return result, err
		}
{{- if hasField . "RunningInstances"}}
		result.RunningInstances = len(stats.Stats)
{{- end}}
{{- if hasField . "Instances"}}
		result.Instances = make([]plugin_models.GetApp_AppInstanceFields, len(stats.Stats))
		for i, stat := range stats.Stats {
			result.Instances[i] = plugin_models.GetApp_AppInstanceFields{
				State:     stat.State,
				Details:   ptrStr(stat.Details),
				Since:     time.Now().Add(-(time.Second * time.Duration(stat.Uptime))),
				CpuUsage:  stat.Usage.CPU,
				DiskQuota: int64(stat.DiskQuota),
				DiskUsage: int64(stat.Usage.Disk),
				MemQuota:  int64(stat.MemoryQuota),
				MemUsage:  int64(stat.Usage.Memory),
			}
		}
{{- end}}
{{- end}}
	}
{{- end}}

{{- if hasGroup . 7}}
	// Routes group: list routes for the app.
	routes, err := c.cfClient.Routes.ListForAppAll(context.Background(), app.GUID, nil)
	if err != nil {
		return result, err
	}
	result.Routes = make([]plugin_models.GetApp_RouteSummary, len(routes))
	for i, route := range routes {
		result.Routes[i] = plugin_models.GetApp_RouteSummary{
			Guid: route.GUID,
			Host: route.Host,
			Domain: plugin_models.GetApp_DomainFields{
				Guid: route.Relationships.Domain.Data.GUID,
			},
			Path: route.Path,
			Port: ptrInt(route.Port),
		}
		// Compute domain name from route URL to avoid an extra API call.
		if slashIndex := strings.Index(route.URL, "/"); slashIndex != -1 {
			result.Routes[i].Domain.Name = route.URL[len(route.Host)+1 : slashIndex]
		} else if len(route.URL) > len(route.Host)+1 {
			result.Routes[i].Domain.Name = route.URL[len(route.Host)+1:]
		}
	}
{{- end}}

{{- if hasGroup . 8}}
	// Services group: list bound service instances.
	_, sis, err := c.cfClient.ServiceCredentialBindings.ListIncludeServiceInstancesAll(context.Background(), &client.ServiceCredentialBindingListOptions{
		AppGUIDs: client.Filter{Values: []string{app.GUID}},
	})
	if err != nil {
		return result, err
	}
	result.Services = make([]plugin_models.GetApp_ServiceSummary, len(sis))
	for i, si := range sis {
		result.Services[i] = plugin_models.GetApp_ServiceSummary{
			Guid: si.GUID,
			Name: si.Name,
		}
	}
{{- end}}

	return result, nil
}
`

const getAppsTemplate = `
// getApps lists all applications the user has access to.
// Populates: {{join .Fields ", "}} ({{groupCount .}} V3 API call(s)).
func (c *V2Compat) getApps() ([]plugin_models.GetAppsModel, error) {
	apps, err := c.cfClient.Applications.ListAll(context.Background(), nil)
	if err != nil {
		return nil, err
	}

	result := make([]plugin_models.GetAppsModel, len(apps))
	for i, app := range apps {
		_ = app
		result[i] = plugin_models.GetAppsModel{
{{- if hasField . "Guid"}}
			Guid: app.GUID,
{{- end}}
{{- if hasField . "Name"}}
			Name: app.Name,
{{- end}}
{{- if hasField . "State"}}
			State: app.State,
{{- end}}
		}

{{- if hasGroup . 1}}
		// Process group (per-app): get process details.
		processes, _, err := c.cfClient.Processes.ListForApp(context.Background(), app.GUID, nil)
		if err != nil {
			return nil, err
		}
		if len(processes) > 0 {
{{- if hasField . "TotalInstances"}}
			result[i].TotalInstances = processes[0].Instances
{{- end}}
{{- if hasField . "Memory"}}
			result[i].Memory = int64(processes[0].MemoryInMB)
{{- end}}
{{- if hasField . "DiskQuota"}}
			result[i].DiskQuota = int64(processes[0].DiskInMB)
{{- end}}

{{- if hasGroup . 2}}
			// Stats group (per-app): get process stats.
			stats, err := c.cfClient.Processes.GetStats(context.Background(), processes[0].GUID)
			if err != nil {
				return nil, err
			}
{{- if hasField . "RunningInstances"}}
			result[i].RunningInstances = len(stats.Stats)
{{- end}}
{{- end}}
		}
{{- end}}

{{- if hasGroup . 3}}
		// Routes group (per-app): list routes.
		routes, err := c.cfClient.Routes.ListForAppAll(context.Background(), app.GUID, nil)
		if err != nil {
			return nil, err
		}
		result[i].Routes = make([]plugin_models.GetAppsRouteSummary, len(routes))
		for j, route := range routes {
			result[i].Routes[j] = plugin_models.GetAppsRouteSummary{
				Guid: route.GUID,
				Host: route.Host,
				Domain: plugin_models.GetAppsDomainFields{
					Guid: route.Relationships.Domain.Data.GUID,
				},
			}
			// Compute domain name from route URL to avoid an extra API call.
			if slashIndex := strings.Index(route.URL, "/"); slashIndex != -1 {
				result[i].Routes[j].Domain.Name = route.URL[len(route.Host)+1 : slashIndex]
			} else if len(route.URL) > len(route.Host)+1 {
				result[i].Routes[j].Domain.Name = route.URL[len(route.Host)+1:]
			}
		}
{{- end}}
	}

	return result, nil
}
`

const getOrgTemplate = `
// getOrg looks up a single organization by name.
// Populates: {{join .Fields ", "}} ({{groupCount .}} V3 API call(s)).
func (c *V2Compat) getOrg(orgName string) (plugin_models.GetOrg_Model, error) {
	org, err := c.cfClient.Organizations.Single(context.Background(), &client.OrganizationListOptions{
		Names: client.Filter{Values: []string{orgName}},
	})
	if err != nil {
		return plugin_models.GetOrg_Model{}, err
	}

	result := plugin_models.GetOrg_Model{
{{- if hasField . "Guid"}}
		Guid: org.GUID,
{{- end}}
{{- if hasField . "Name"}}
		Name: org.Name,
{{- end}}
	}

{{- if hasGroup . 3}}
	// Domains group: list domains for this organization.
	domains, err := c.cfClient.Domains.ListForOrganizationAll(context.Background(), org.GUID, nil)
	if err != nil {
		return result, err
	}
	for _, domain := range domains {
		owningOrg := ""
		shared := domain.Relationships.Organization.Data == nil
		if !shared {
			owningOrg = domain.Relationships.Organization.Data.GUID
		}
		result.Domains = append(result.Domains, plugin_models.GetOrg_Domains{
			Guid:                   domain.GUID,
			Name:                   domain.Name,
			OwningOrganizationGuid: owningOrg,
			Shared:                 shared,
		})
	}
{{- end}}

{{- if hasGroup . 2}}
	// Spaces group: list spaces in this organization.
	spaces, err := c.cfClient.Spaces.ListAll(context.Background(), &client.SpaceListOptions{
		OrganizationGUIDs: client.Filter{Values: []string{org.GUID}},
	})
	if err != nil {
		return result, err
	}
	for _, space := range spaces {
		result.Spaces = append(result.Spaces, plugin_models.GetOrg_Space{
			Guid: space.GUID,
			Name: space.Name,
		})
	}
{{- end}}

{{- if hasGroup . 4}}
	// SpaceQuotas group: list space quotas in this organization.
	spaceQuotas, err := c.cfClient.SpaceQuotas.ListAll(context.Background(), &client.SpaceQuotaListOptions{
		OrganizationGUIDs: client.Filter{Values: []string{org.GUID}},
	})
	if err != nil {
		return result, err
	}
	for _, sq := range spaceQuotas {
		result.SpaceQuotas = append(result.SpaceQuotas, plugin_models.GetOrg_SpaceQuota{
			Guid:                    sq.GUID,
			Name:                    sq.Name,
			MemoryLimit:             ptrInt64(sq.Apps.TotalMemoryInMB),
			InstanceMemoryLimit:     ptrInt64(sq.Apps.PerProcessMemoryInMB),
			RoutesLimit:             ptrInt(sq.Routes.TotalRoutes),
			ServicesLimit:           ptrInt(sq.Services.TotalServiceInstances),
			NonBasicServicesAllowed: sq.Services.PaidServicesAllowed,
		})
	}
{{- end}}

{{- if hasGroup . 1}}
	// QuotaDefinition group: get the organization quota.
	// Note: QuotaDefinition field uses QuotaFields type — populated if the org has a quota relationship.
	// TODO: Implement org quota lookup when QuotaDefinition field is needed.
{{- end}}

	return result, nil
}
`

const getSpaceTemplate = `
// getSpace looks up a single space by name.
// Populates: {{join .Fields ", "}} ({{groupCount .}} V3 API call(s)).
func (c *V2Compat) getSpace(spaceName string) (plugin_models.GetSpace_Model, error) {
	space, err := c.cfClient.Spaces.Single(context.Background(), &client.SpaceListOptions{
		Names: client.Filter{Values: []string{spaceName}},
	})
	if err != nil {
		return plugin_models.GetSpace_Model{}, err
	}

	result := plugin_models.GetSpace_Model{
		GetSpaces_Model: plugin_models.GetSpaces_Model{
{{- if hasField . "Guid"}}
			Guid: space.GUID,
{{- end}}
{{- if hasField . "Name"}}
			Name: space.Name,
{{- end}}
		},
	}

{{- if hasField . "Organization"}}
	// Organization: look up the parent org.
	org, err := c.cfClient.Organizations.Get(context.Background(), space.Relationships.Organization.Data.GUID)
	if err != nil {
		return result, err
	}
	result.Organization = plugin_models.GetSpace_Orgs{
		Guid: org.GUID,
		Name: org.Name,
	}
{{- end}}

{{- if hasGroup . 1}}
	// Applications group: list apps in this space.
	spaceFilter := client.Filter{Values: []string{space.GUID}}
	apps, err := c.cfClient.Applications.ListAll(context.Background(), &client.AppListOptions{SpaceGUIDs: spaceFilter})
	if err != nil {
		return result, err
	}
	result.Applications = make([]plugin_models.GetSpace_Apps, len(apps))
	for i, app := range apps {
		result.Applications[i] = plugin_models.GetSpace_Apps{
			Name: app.Name,
			Guid: app.GUID,
		}
	}
{{- end}}

{{- if hasGroup . 2}}
	// ServiceInstances group: list service instances in this space.
	{{- if not (hasGroup . 1)}}
	spaceFilter := client.Filter{Values: []string{space.GUID}}
	{{- end}}
	sis, err := c.cfClient.ServiceInstances.ListAll(context.Background(), &client.ServiceInstanceListOptions{SpaceGUIDs: spaceFilter})
	if err != nil {
		return result, err
	}
	result.ServiceInstances = make([]plugin_models.GetSpace_ServiceInstance, len(sis))
	for i, si := range sis {
		result.ServiceInstances[i] = plugin_models.GetSpace_ServiceInstance{
			Guid: si.GUID,
			Name: si.Name,
		}
	}
{{- end}}

{{- if hasGroup . 3}}
	// Domains group: list domains for the parent organization.
	{{- if not (hasField . "Organization")}}
	org, err := c.cfClient.Organizations.Get(context.Background(), space.Relationships.Organization.Data.GUID)
	if err != nil {
		return result, err
	}
	{{- end}}
	domains, err := c.cfClient.Domains.ListAll(context.Background(), &client.DomainListOptions{
		OrganizationGUIDs: client.Filter{Values: []string{org.GUID}},
	})
	if err != nil {
		return result, err
	}
	result.Domains = make([]plugin_models.GetSpace_Domains, len(domains))
	for i, domain := range domains {
		owningOrg := ""
		if domain.Relationships.Organization.Data != nil {
			owningOrg = domain.Relationships.Organization.Data.GUID
		}
		result.Domains[i] = plugin_models.GetSpace_Domains{
			Guid:                   domain.GUID,
			Name:                   domain.Name,
			OwningOrganizationGuid: owningOrg,
			Shared:                 domain.Relationships.Organization.Data == nil,
		}
	}
{{- end}}

{{- if hasGroup . 5}}
	// SpaceQuota group: get the space quota if assigned.
	if space.Relationships.Quota.Data != nil {
		quota, err := c.cfClient.SpaceQuotas.Get(context.Background(), space.Relationships.Quota.Data.GUID)
		if err != nil {
			return result, err
		}
		result.SpaceQuota = plugin_models.GetSpace_SpaceQuota{
			Guid:                    quota.GUID,
			Name:                    quota.Name,
			MemoryLimit:             ptrInt64(quota.Apps.TotalMemoryInMB),
			InstanceMemoryLimit:     ptrInt64(quota.Apps.PerProcessMemoryInMB),
			RoutesLimit:             ptrInt(quota.Routes.TotalRoutes),
			ServicesLimit:           ptrInt(quota.Services.TotalServiceInstances),
			NonBasicServicesAllowed: quota.Services.PaidServicesAllowed,
		}
	}
{{- end}}

	return result, nil
}
`

const getServiceTemplate = `
// getService looks up a single service instance by name in the current space.
// Populates: {{join .Fields ", "}} ({{groupCount .}} V3 API call(s)).
func (c *V2Compat) getService(serviceInstance string) (plugin_models.GetService_Model, error) {
	si, err := c.cfClient.ServiceInstances.Single(context.Background(), &client.ServiceInstanceListOptions{
		Names:      client.Filter{Values: []string{serviceInstance}},
		SpaceGUIDs: client.Filter{Values: []string{c.spaceGUID}},
	})
	if err != nil {
		return plugin_models.GetService_Model{}, err
	}

	result := plugin_models.GetService_Model{
{{- if hasField . "Guid"}}
		Guid: si.GUID,
{{- end}}
{{- if hasField . "Name"}}
		Name: si.Name,
{{- end}}
{{- if hasField . "DashboardUrl"}}
		DashboardUrl: ptrStr(si.DashboardURL),
{{- end}}
{{- if hasField . "IsUserProvided"}}
		IsUserProvided: si.Type == "user-provided",
{{- end}}
{{- if hasField . "LastOperation"}}
		LastOperation: plugin_models.GetService_LastOperation{
			Type:        si.LastOperation.Type,
			State:       si.LastOperation.State,
			Description: si.LastOperation.Description,
			CreatedAt:   si.LastOperation.CreatedAt.String(),
			UpdatedAt:   si.LastOperation.UpdatedAt.String(),
		},
{{- end}}
	}

{{- if hasField . "ServicePlan"}}
	// ServicePlan: fetch the plan details.
	servicePlan, err := c.cfClient.ServicePlans.Get(context.Background(), si.Relationships.ServicePlan.Data.GUID)
	if err != nil {
		return result, err
	}
	result.ServicePlan = plugin_models.GetService_ServicePlan{
		Name: servicePlan.Name,
		Guid: servicePlan.GUID,
	}

{{- if hasField . "ServiceOffering"}}
	// ServiceOffering: fetch the offering via the plan.
	serviceOffering, err := c.cfClient.ServiceOfferings.Get(context.Background(), servicePlan.Relationships.ServiceOffering.Data.GUID)
	if err != nil {
		return result, err
	}
	result.ServiceOffering = plugin_models.GetService_ServiceFields{
		Name:             serviceOffering.Name,
		DocumentationUrl: serviceOffering.DocumentationURL,
	}
{{- end}}
{{- end}}

	return result, nil
}
`

const getServicesTemplate = `
// getServices lists service instances in the current space.
// Populates: {{join .Fields ", "}} ({{groupCount .}} V3 API call(s)).
func (c *V2Compat) getServices() ([]plugin_models.GetServices_Model, error) {
	serviceInstances, err := c.cfClient.ServiceInstances.ListAll(context.Background(), &client.ServiceInstanceListOptions{
		SpaceGUIDs: client.Filter{Values: []string{c.spaceGUID}},
	})
	if err != nil {
		return nil, err
	}

	var results []plugin_models.GetServices_Model
	for _, si := range serviceInstances {
		result := plugin_models.GetServices_Model{
{{- if hasField . "Guid"}}
			Guid: si.GUID,
{{- end}}
{{- if hasField . "Name"}}
			Name: si.Name,
{{- end}}
{{- if hasField . "IsUserProvided"}}
			IsUserProvided: si.Type == "user-provided",
{{- end}}
{{- if hasField . "LastOperation"}}
			LastOperation: plugin_models.GetServices_LastOperation{
				Type:  si.LastOperation.Type,
				State: si.LastOperation.State,
			},
{{- end}}
		}

{{- if hasField . "ApplicationNames"}}
		// ApplicationNames: fetch bound apps for this service instance.
		_, apps, err := c.cfClient.ServiceCredentialBindings.ListIncludeAppsAll(context.Background(), &client.ServiceCredentialBindingListOptions{
			ServiceInstanceGUIDs: client.Filter{Values: []string{si.GUID}},
		})
		if err != nil {
			return nil, err
		}
		for _, app := range apps {
			result.ApplicationNames = append(result.ApplicationNames, app.Name)
		}
{{- end}}

{{- if hasField . "ServicePlan"}}
		// ServicePlan: fetch plan details.
		servicePlan, err := c.cfClient.ServicePlans.Get(context.Background(), si.Relationships.ServicePlan.Data.GUID)
		if err != nil {
			return nil, err
		}
		result.ServicePlan = plugin_models.GetServices_ServicePlan{
			Name: servicePlan.Name,
			Guid: servicePlan.GUID,
		}

{{- if hasField . "Service"}}
		// Service: fetch the service offering via the plan.
		serviceOffering, err := c.cfClient.ServiceOfferings.Get(context.Background(), servicePlan.Relationships.ServiceOffering.Data.GUID)
		if err != nil {
			return nil, err
		}
		result.Service = plugin_models.GetServices_ServiceFields{
			Name: serviceOffering.Name,
		}
{{- end}}
{{- end}}

		results = append(results, result)
	}

	return results, nil
}
`

const getOrgUsersTemplate = `
// getOrgUsers lists users and their roles in an organization.
// Populates: {{join .Fields ", "}} ({{groupCount .}} V3 API call(s)).
func (c *V2Compat) getOrgUsers(orgName string, args ...string) ([]plugin_models.GetOrgUsers_Model, error) {
	org, err := c.cfClient.Organizations.Single(context.Background(), &client.OrganizationListOptions{
		Names: client.Filter{Values: []string{orgName}},
	})
	if err != nil {
		return nil, err
	}

	roles, users, err := c.cfClient.Roles.ListIncludeUsersAll(context.Background(), &client.RoleListOptions{
		OrganizationGUIDs: client.Filter{Values: []string{org.GUID}},
	})
	if err != nil {
		return nil, err
	}

	userDict := make(map[string][]string)
	for _, role := range roles {
		userDict[role.Relationships.User.Data.GUID] = append(userDict[role.Relationships.User.Data.GUID], role.Type)
	}

	var result []plugin_models.GetOrgUsers_Model
	for _, user := range users {
		if userRoles := userDict[user.GUID]; userRoles != nil {
			result = append(result, plugin_models.GetOrgUsers_Model{
{{- if hasField . "Guid"}}
				Guid: user.GUID,
{{- end}}
{{- if hasField . "Username"}}
				Username: ptrStr(user.Username),
{{- end}}
{{- if hasField . "Roles"}}
				Roles: userRoles,
{{- end}}
			})
		}
	}

	return result, nil
}
`

const getSpaceUsersTemplate = `
// getSpaceUsers lists users and their roles in a space.
// Populates: {{join .Fields ", "}} ({{groupCount .}} V3 API call(s)).
func (c *V2Compat) getSpaceUsers(orgName string, spaceName string) ([]plugin_models.GetSpaceUsers_Model, error) {
	org, err := c.cfClient.Organizations.Single(context.Background(), &client.OrganizationListOptions{
		Names: client.Filter{Values: []string{orgName}},
	})
	if err != nil {
		return nil, err
	}

	space, err := c.cfClient.Spaces.Single(context.Background(), &client.SpaceListOptions{
		Names:             client.Filter{Values: []string{spaceName}},
		OrganizationGUIDs: client.Filter{Values: []string{org.GUID}},
	})
	if err != nil {
		return nil, err
	}

	roles, users, err := c.cfClient.Roles.ListIncludeUsersAll(context.Background(), &client.RoleListOptions{
		SpaceGUIDs: client.Filter{Values: []string{space.GUID}},
	})
	if err != nil {
		return nil, err
	}

	userDict := make(map[string][]string)
	for _, role := range roles {
		userDict[role.Relationships.User.Data.GUID] = append(userDict[role.Relationships.User.Data.GUID], role.Type)
	}

	result := make([]plugin_models.GetSpaceUsers_Model, len(users))
	for i, user := range users {
		result[i] = plugin_models.GetSpaceUsers_Model{
{{- if hasField . "Guid"}}
			Guid: user.GUID,
{{- end}}
{{- if hasField . "Username"}}
			Username: ptrStr(user.Username),
{{- end}}
{{- if hasField . "Roles"}}
			Roles: userDict[user.GUID],
{{- end}}
		}
	}

	return result, nil
}
`
